sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - stable
before_install:
  - "npm config set spin false"
before_script:
  - "npm install jshint"
  - "npm install mocha"
